[package]
name = "serde_path_to_error"
version = "0.1.2" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Path to the element that failed to deserialize"
repository = "https://github.com/dtolnay/path-to-error"
readme = "README.md"
edition = "2018"

[dependencies]
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"

[badges]
travis-ci = { repository = "dtolnay/path-to-error" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
